# Generated by Django 4.0.3 on 2022-04-13 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task_manager', '0006_remove_task_assigned_to_task_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='supervised_by',
            field=models.ManyToManyField(related_name='supervised_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
