# Generated by Django 4.0.3 on 2022-04-13 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager', '0008_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('EML', 'Email'), ('STM', 'System')], default='STM', max_length=3),
        ),
    ]
