# Generated by Django 4.0.3 on 2022-04-05 22:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import helpers.upload_file_name


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arrestee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=100)),
                ('county_of_residence', models.CharField(max_length=100)),
                ('constituency_of_residence', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('age', models.IntegerField()),
                ('posted_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ChargeSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ChargeSheet_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=3, unique=True)),
                ('nationality', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Evidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.FloatField()),
                ('description', models.TextField()),
                ('posted_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='IPRS_Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(max_length=100)),
                ('passport_no', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=30)),
                ('county_of_birth', models.CharField(max_length=30)),
                ('district_of_birth', models.CharField(max_length=30)),
                ('division_of_birth', models.CharField(max_length=30)),
                ('location_of_birth', models.CharField(max_length=30)),
                ('date_of_birth', models.DateTimeField()),
                ('mug_shot', models.ImageField(upload_to=helpers.upload_file_name.IPRS_person_mugshot_directory_path)),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.country')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Occurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('posted_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PoliceStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Warrant_of_arrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Reporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=254)),
                ('county_of_residence', models.CharField(max_length=100)),
                ('sub_county_of_residence', models.CharField(max_length=100)),
                ('iprs_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person')),
            ],
        ),
        migrations.CreateModel(
            name='PoliceOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_number', models.CharField(max_length=100)),
                ('email_address', models.EmailField(max_length=254)),
                ('mobile_phone', models.CharField(max_length=30)),
                ('mug_shot', models.ImageField(upload_to=helpers.upload_file_name.policeOfficer_mugshot_directory_path)),
                ('iprs_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.rank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PoliceCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_no', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=30)),
                ('police_station', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.policestation')),
            ],
        ),
        migrations.CreateModel(
            name='OccurrenceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
                ('category', models.ManyToManyField(to='vps.occurrencecategory')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.occurrence')),
            ],
        ),
        migrations.AddField(
            model_name='occurrence',
            name='police_officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.policeofficer'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='police_station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.policestation'),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='reporter',
            field=models.ManyToManyField(blank=True, to='vps.reporter'),
        ),
        migrations.CreateModel(
            name='Next_of_keen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('relationship', models.CharField(max_length=30)),
                ('arrestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.arrestee')),
            ],
        ),
        migrations.CreateModel(
            name='MugShots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('left_view', models.ImageField(upload_to=helpers.upload_file_name.arrestee_mugshot_directory_path)),
                ('front_view', models.ImageField(upload_to=helpers.upload_file_name.arrestee_mugshot_directory_path)),
                ('right_view', models.ImageField(upload_to=helpers.upload_file_name.arrestee_mugshot_directory_path)),
                ('arrestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.arrestee')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('units', models.CharField(max_length=30)),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('serial_no', models.CharField(max_length=100)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.itemcategory')),
            ],
        ),
        migrations.CreateModel(
            name='FingerPrints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb', models.ImageField(upload_to=helpers.upload_file_name.arrestee_fingerprint_directory_path)),
                ('left_hand', models.ImageField(upload_to=helpers.upload_file_name.arrestee_fingerprint_directory_path)),
                ('right_hand', models.ImageField(upload_to=helpers.upload_file_name.arrestee_fingerprint_directory_path)),
                ('arrestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.arrestee')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=helpers.upload_file_name.evidence_image_directory_path)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.evidence')),
            ],
        ),
        migrations.AddField(
            model_name='evidence',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.evidencecategory'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='item',
            field=models.ManyToManyField(to='vps.item'),
        ),
        migrations.AddField(
            model_name='evidence',
            name='officers_in_charge',
            field=models.ManyToManyField(to='vps.policeofficer'),
        ),
        migrations.CreateModel(
            name='CourtFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('court_file_no', models.CharField(max_length=100)),
                ('sentence_court', models.CharField(max_length=100)),
                ('date_of_mentioning', models.DateTimeField()),
                ('date_of_sentencing', models.DateTimeField()),
                ('charge_sheet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.chargesheet')),
            ],
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='complainant',
            field=models.ManyToManyField(related_name='complainant', to='vps.chargesheet_person'),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.occurrence'),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='offense',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.offense'),
        ),
        migrations.AddField(
            model_name='chargesheet',
            name='witness',
            field=models.ManyToManyField(related_name='witness', to='vps.chargesheet_person'),
        ),
        migrations.AddField(
            model_name='arrestee',
            name='cell',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.policecell'),
        ),
        migrations.AddField(
            model_name='arrestee',
            name='iprs_person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person'),
        ),
        migrations.AddField(
            model_name='arrestee',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.occurrence'),
        ),
        migrations.AddField(
            model_name='arrestee',
            name='warrant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.warrant_of_arrest'),
        ),
    ]
