# Generated by Django 4.0.3 on 2022-04-05 23:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0002_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='iprs_person',
            name='gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.gender'),
        ),
    ]
