# Generated by Django 4.0.3 on 2022-04-06 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0004_alter_iprs_person_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprs_person',
            name='middle_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
