# Generated by Django 4.0.3 on 2022-04-08 22:02

from django.db import migrations, models
import helpers.upload_file_name


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0005_alter_iprs_person_middle_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iprs_person',
            name='id_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprs_person',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='iprs_person',
            name='mug_shot',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_file_name.IPRS_person_mugshot_directory_path),
        ),
        migrations.AlterField(
            model_name='iprs_person',
            name='passport_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
