# Generated by Django 4.0.3 on 2022-04-10 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0006_alter_iprs_person_id_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rank',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
