# Generated by Django 4.0.3 on 2022-04-10 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vps', '0007_alter_rank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='iprs_person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person'),
        ),
        migrations.AlterField(
            model_name='policeofficer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
