# Generated by Django 4.0.3 on 2022-05-13 03:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0008_alter_policeofficer_iprs_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='policeofficer',
            name='police_station',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vps.policestation'),
        ),
    ]
