# Generated by Django 4.0.3 on 2022-05-13 05:59

from django.db import migrations, models
import helpers.upload_file_name


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0009_policeofficer_police_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='mug_shot',
            field=models.ImageField(blank=True, null=True, upload_to=helpers.upload_file_name.policeOfficer_mugshot_directory_path),
        ),
    ]
