# Generated by Django 4.0.3 on 2022-05-14 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0011_occurrencecategoryinput'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencecategoryinput',
            name='choices',
            field=models.TextField(blank=True, null=True),
        ),
    ]
