# Generated by Django 4.0.3 on 2022-05-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0012_alter_occurrencecategoryinput_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecategoryinput',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
