# Generated by Django 4.0.3 on 2022-05-15 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0014_remove_occurrencedetail_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='occurrence',
            old_name='reporter',
            new_name='reporters',
        ),
        migrations.AlterField(
            model_name='occurrence',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
