# Generated by Django 4.0.3 on 2022-05-15 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0015_rename_reporter_occurrence_reporters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='reporters',
        ),
        migrations.AddField(
            model_name='reporter',
            name='occurrence',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vps.occurrence'),
            preserve_default=False,
        ),
    ]
