# Generated by Django 4.0.3 on 2022-05-17 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0016_remove_occurrence_reporters_reporter_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='module',
            field=models.CharField(default='OB', max_length=30),
            preserve_default=False,
        ),
    ]
