# Generated by Django 4.0.3 on 2022-06-30 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0020_alter_iprs_person_county_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=30)),
                ('model', models.CharField(max_length=100)),
                ('units', models.CharField(max_length=30)),
                ('quantity', models.FloatField()),
                ('description', models.TextField()),
                ('serial_no', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='count',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='description',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='item',
        ),
        migrations.RemoveField(
            model_name='evidence',
            name='officers_in_charge',
        ),
        # migrations.RemoveField(
        #     model_name='evidenceitemimage',
        #     name='evidence',
        # ),
        migrations.AddField(
            model_name='evidence',
            name='officer_incharge',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='officer_incharge', to='vps.policeofficer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evidence',
            name='officers_involved',
            field=models.ManyToManyField(related_name='officers_involved', to='vps.policeofficer'),
        ),
        migrations.RenameModel(
            old_name='ItemCategory',
            new_name='EvidenceItemCategory',
        ),
        migrations.RenameModel(
            old_name='EvidenceImage',
            new_name='EvidenceItemImage',
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.evidenceitemcategory'),
        ),
        migrations.AddField(
            model_name='evidenceitem',
            name='evidence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.evidence'),
        ),
        migrations.AddField(
            model_name='evidenceitemimage',
            name='evidence_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vps.evidenceitem'),
            preserve_default=False,
        ),
    ]
