# Generated by Django 4.0.3 on 2022-06-30 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0021_evidenceitem_remove_evidence_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evidenceitemimage',
            name='evidence',
        ),
    ]
