# Generated by Django 4.0.3 on 2022-07-01 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0023_evidence_description_evidence_evidence_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenceitemcategory',
            old_name='model',
            new_name='item_models',
        ),
        migrations.RenameField(
            model_name='evidenceitemcategory',
            old_name='make',
            new_name='makes',
        ),
    ]
