# Generated by Django 4.0.3 on 2022-07-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0025_rename_unit_evidenceitemcategory_units'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidence',
            old_name='category',
            new_name='evidence_category',
        ),
        migrations.AlterField(
            model_name='evidence',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
