# Generated by Django 4.0.3 on 2022-07-01 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0026_rename_category_evidence_evidence_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evidenceitemimage',
            old_name='evidence_item',
            new_name='evidence',
        ),
    ]
