# Generated by Django 4.0.3 on 2022-07-14 07:50

from django.db import migrations, models
import django.db.models.deletion
import helpers.upload_file_name


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0028_alter_evidenceitemimage_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_reg_no', models.CharField(max_length=50)),
                ('vehicle_identification_no', models.CharField(max_length=50)),
                ('make', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('organization', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficOffender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('county_of_incident', models.CharField(max_length=30)),
                ('constituency', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('age', models.CharField(max_length=8)),
                ('image', models.ImageField(blank=True, null=True, upload_to=helpers.upload_file_name.offender_image_directory_path)),
                ('Vehicle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.vehicle')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.gender')),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dl_number', models.CharField(max_length=20)),
                ('expiry_date', models.DateTimeField()),
                ('IPRS_Person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person')),
            ],
        ),
    ]
