# Generated by Django 4.0.3 on 2022-08-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0030_permissionmodule_remove_trafficoffender_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='is_incomplete',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='permission',
            name='name',
            field=models.CharField(choices=[('add', 'Add'), ('update', 'Update'), ('delete', 'Delete')], max_length=30),
        ),
    ]
