# Generated by Django 4.0.3 on 2022-08-13 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0031_occurrence_is_incomplete_alter_permission_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='occurrence',
            name='is_incomplete',
        ),
        migrations.AddField(
            model_name='occurrence',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
