# Generated by Django 4.0.3 on 2022-08-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0032_remove_occurrence_is_incomplete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecategory',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
