# Generated by Django 4.0.3 on 2022-08-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0033_occurrencecategory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='OccurrenceCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ob_no', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now_add=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='reporter',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
