# Generated by Django 4.0.3 on 2022-08-25 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0035_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Location',
        ),
    ]
