# Generated by Django 4.0.3 on 2022-08-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0036_delete_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='lat',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='occurrence',
            name='long',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
