# Generated by Django 4.0.3 on 2022-09-17 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0037_occurrence_lat_occurrence_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrence',
            name='narrative',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
