# Generated by Django 4.0.3 on 2022-09-23 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0038_occurrence_narrative'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrestee',
            name='occurrence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='arrests', to='vps.occurrence'),
        ),
    ]
