# Generated by Django 4.0.3 on 2022-09-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0039_alter_arrestee_occurrence'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecategoryinput',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
