# Generated by Django 4.0.3 on 2022-09-30 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0040_occurrencecategoryinput_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredReporter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_no', models.CharField(blank=True, max_length=100)),
                ('passport_no', models.CharField(blank=True, max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('county_of_birth', models.CharField(blank=True, max_length=30)),
                ('district_of_birth', models.CharField(blank=True, max_length=30)),
                ('division_of_birth', models.CharField(blank=True, max_length=30)),
                ('location_of_birth', models.CharField(blank=True, max_length=30)),
                ('date_of_birth', models.DateTimeField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=30)),
                ('email_address', models.EmailField(blank=True, max_length=254)),
                ('county_of_residence', models.CharField(blank=True, max_length=100)),
                ('sub_county_of_residence', models.CharField(blank=True, max_length=100)),
                ('constituency_of_residence', models.CharField(blank=True, max_length=100)),
                ('ward_of_residence', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.gender')),
                ('nationality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.country')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unregistered_reporters', to='vps.occurrence')),
            ],
        ),
    ]
