# Generated by Django 4.0.3 on 2022-10-04 05:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0042_alter_reporter_county_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vps.policestation'),
        ),
    ]
