# Generated by Django 4.0.3 on 2022-10-28 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0043_alter_policeofficer_police_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='arrestee',
            old_name='constituency_of_residence',
            new_name='sub_county_of_residence',
        ),
        migrations.RemoveField(
            model_name='arrestee',
            name='age',
        ),
        migrations.RemoveField(
            model_name='arrestee',
            name='remarks',
        ),
        migrations.AddField(
            model_name='arrestee',
            name='email',
            field=models.EmailField(default='example@email.com', max_length=254),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Gang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('arrestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.arrestee')),
            ],
        ),
        migrations.CreateModel(
            name='Accomplice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('residence', models.CharField(max_length=100)),
                ('remarks', models.TextField()),
                ('arrestee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.arrestee')),
            ],
        ),
    ]
