# Generated by Django 4.0.3 on 2022-10-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0044_rename_constituency_of_residence_arrestee_sub_county_of_residence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrestee',
            name='cell',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='vps.policecell'),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='county_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='sub_county_of_residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='warrant',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='vps.warrant_of_arrest'),
        ),
    ]
