# Generated by Django 4.0.3 on 2022-10-28 22:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0045_alter_arrestee_cell_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arrestee',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vps.policecell'),
        ),
        migrations.AlterField(
            model_name='arrestee',
            name='warrant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vps.warrant_of_arrest'),
        ),
    ]
