# Generated by Django 4.0.3 on 2022-10-29 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0047_arrestee_arresting_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrestee',
            name='arrestee_condition',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='arrestee',
            name='cell_type',
            field=models.CharField(default='Men', max_length=30),
            preserve_default=False,
        ),
    ]
