# Generated by Django 4.0.3 on 2022-10-31 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0048_arrestee_arrestee_condition_arrestee_cell_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomplice',
            name='alias',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accomplice',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='accomplice',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='accomplice',
            name='residence',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gang',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='gang',
            name='remarks',
            field=models.TextField(blank=True),
        ),
    ]
