# Generated by Django 4.0.3 on 2022-10-31 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0049_alter_accomplice_alias_alter_accomplice_name_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Next_of_keen',
            new_name='Next_of_kin',
        ),
    ]
