# Generated by Django 4.0.3 on 2022-10-31 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0050_rename_next_of_keen_next_of_kin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_of_kin',
            name='phone',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
