# Generated by Django 4.0.3 on 2022-11-04 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0053_alter_arrestee_date_of_arrest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='next_of_kin',
            name='arrestee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_of_kins', to='vps.arrestee'),
        ),
    ]
