# Generated by Django 4.0.3 on 2022-11-23 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0056_remove_arrestee_warrant_arrestee_warrants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso_code',
            field=models.CharField(default='KE', max_length=10),
            preserve_default=False,
        ),
    ]
