# Generated by Django 4.0.3 on 2022-11-29 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0059_remove_fingerprints_left_hand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policeofficer',
            name='police_station',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='vps.policestation'),
            preserve_default=False,
        ),
    ]
