# Generated by Django 4.0.3 on 2022-11-29 09:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0060_alter_policeofficer_police_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='fingerprints',
            name='police_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vps.policestation'),
        ),
        migrations.AddField(
            model_name='fingerprints',
            name='posted_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
