# Generated by Django 4.0.3 on 2022-12-18 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0063_occurrencecategoryinput_dependency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencecategoryinput',
            name='dependency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dependencies', to='vps.occurrencecategoryinput'),
        ),
    ]
