# Generated by Django 4.0.3 on 2022-12-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0064_alter_occurrencecategoryinput_dependency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='occurrencecategoryinput',
            name='choices',
            field=models.TextField(blank=True, default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='occurrencecategoryinput',
            name='type',
            field=models.CharField(choices=[('text', 'Single line Text'), ('textarea', 'Multi line Text '), ('select', 'Select'), ('radio', 'Radio'), ('checkbox', 'Checkbox'), ('date', 'Date')], max_length=10),
        ),
    ]
