# Generated by Django 4.0.3 on 2022-12-18 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0066_inspection_trafficsubject_unregisteredtrafficsubject_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='vehicle_reg_no',
            new_name='reg_no',
        ),
    ]
