# Generated by Django 4.0.3 on 2022-12-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0068_inspection_date_modified_inspection_date_posted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trafficsubject',
            name='dl_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unregisteredtrafficsubject',
            name='dl_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
