# Generated by Django 4.0.3 on 2023-01-18 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0070_insurancepolicy_registeredvehicle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(max_length=50)),
                ('license_class', models.CharField(max_length=50)),
                ('date_expiry', models.DateTimeField()),
                ('iprs_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person')),
            ],
        ),
    ]
