# Generated by Django 4.0.3 on 2023-01-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0071_drivinglicense'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficOffender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('county_of_residence', models.CharField(blank=True, max_length=100)),
                ('sub_county_of_residence', models.CharField(blank=True, max_length=100)),
                ('date_of_arrest', models.DateField()),
                ('time_of_arrest', models.TimeField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(auto_now_add=True)),
                ('iprs_person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vps.iprs_person')),
                ('occurrence', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traffic_offenders', to='vps.occurrence')),
            ],
        ),
    ]
