# Generated by Django 4.0.3 on 2023-01-18 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vps', '0073_rename_date_of_arrest_trafficoffender_date_of_booking_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='occurrencecategory',
            name='module',
            field=models.CharField(default='ob', max_length=30),
            preserve_default=False,
        ),
    ]
