FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive
ENV POETRY_VIRTUALENVS_IN_PROJECT=false
ENV TALKED_CONFIG_PATH=config.toml

# hadolint ignore=DL3013
RUN set -ex; \
    groupadd user1; \
    useradd --shell /bin/bash --gid user1 --create-home user1; \
    apt-get update; \
    apt-get install -y --no-install-recommends \
        python3 \
        python3-dev \
        python3-pip \
        python3-venv \
        sudo \
        uwsgi \
    ; \
    pip3 install --no-cache-dir poetry; \
    rm -rf /var/lib/apt/lists/*; \
    echo user1 ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/user1;

RUN set -ex; \
    mkdir -p /home/user1/user1; \
    chown user1:user1 /home/user1/user1; \
    # Symlink python3 to python as poetry seems to be having some issues when python isn't present
    ln -s /usr/bin/python3 /usr/bin/python;

WORKDIR /home/user1/user1

COPY entrypoint.sh /entrypoint.sh
RUN ["chmod", "+x", "/entrypoint.sh"]
ENTRYPOINT [ "/entrypoint.sh" ]
